### ISSUE TITLE
Equations without `-terse` not showing results

### ISSUE THREAD

**Issue by DeeeeLAN** [svenstaro/rofi-calc#88] opened 2022-08-25 20:28 UTC
I tried `60x + 30 = 150` and it provided the result as just the input equation. If I add `-terse`, it gives the `x = 2` output in the history, but not the input equation. The gif on the homepage shows the result popping up after the equation input - is there something special I need to do to make that happen? 

I am on Arch. My rofi has a custom theme so it is possible that is messing with it, but I ran without the config in place and I still didn't see a result.

**Comment by takase1121** [comment] 2022-09-18 04:09
Same issue on Arch, it did not work with the default theme either.

**Comment by CowCowFuture** [comment] 2022-11-21 03:46
On Arch as well. I tested without my config and I'm getting the same results as you.

**Comment by alba4k** [comment] 2023-11-18 20:04
-terse however makes hides the rest of the calculation, which is useful to have in case you need to double check anything, as qalculate can use quite some fantasy in its interpretation of some expressions

![immagine](https://github.com/svenstaro/rofi-calc/assets/84153269/62feb442-b944-4c4c-bde1-2f2ec799dbdf)

Wouldn't it be possible to print both lines of qalc's output?

![immagine](https://github.com/svenstaro/rofi-calc/assets/84153269/10f6592a-b0ea-4d5f-b4e9-90104f8be882)

**Comment by tuncenator** [comment] 2023-11-22 09:13
I have the very same issue on Arch and would love to have a solution for this.

**Comment by mcepl** [comment] 2024-08-01 16:14
duplicate of #124 (because there is an explanation)

**Comment by alba4k** [comment] 2024-08-01 17:43
how is an issue 2 years older a duplicate 😅

**Closed** 2024-12-18 21:21 UTC

**Comment by mcepl** [comment] 2024-12-18 23:04
> how is an issue 2 years older a duplicate 😅

Read my comment again, please.

**Comment by alba4k** [comment] 2024-12-18 23:09
this issue was not the duplicate

#152 was
